name: Debian

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        ubuntu-version: [20.04, 22.04, 24.04]
    runs-on: ubuntu-${{ matrix.ubuntu-version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: "recursive"

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake build-essential automake libtool pkg-config curl libminiupnpc-dev libjemalloc-dev libzstd-dev zlib1g-dev ocl-icd-opencl-dev qtwebengine5-dev fakeroot devscripts debhelper dpkg-dev

      - name: Install CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.21
        with:
          cuda: '12.4.0'
          method: network
          sub-packages: '["nvcc", "cudart"]'

      - name: Build Debian package
        run: |
          ARCH=amd64 DIST=ubuntu-${{ matrix.ubuntu-version }} ./make_debian.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-${{ matrix.ubuntu-version }}
          path: ./*.deb
      
      - name: Upload a Build Artifact to release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.deb
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true